services:
  openodha-auth:
    image: animeshchouhan/openodha-auth:latest
    ports:
      - 9000:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_ENV: DEV
      REDIS_PASSWORD_LOC: /run/secrets/REDIS_PASSWORD
      POSTGRES_PASSWORD_LOC: /run/secrets/POSTGRES_PASSWORD

    secrets:
      - REDIS_PASSWORD
      - POSTGRES_PASSWORD

secrets:
  REDIS_PASSWORD:
    file: ./redis-passwd
  POSTGRES_PASSWORD:
    file: ./postgres-passwd
